//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chashavshavon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chashavshavon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://remotechashavshavon.appspot.com.
        /// </summary>
        internal static string AppURL {
            get {
                return ResourceManager.GetString("AppURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlueMarble {
            get {
                object obj = ResourceManager.GetObject("BlueMarble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonBackground {
            get {
                object obj = ResourceManager.GetObject("ButtonBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_date {
            get {
                object obj = ResourceManager.GetObject("calendar_date", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chash {
            get {
                object obj = ResourceManager.GetObject("chash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ChashFile {
            get {
                object obj = ResourceManager.GetObject("ChashFile", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.compute.co.il.
        /// </summary>
        internal static string ComputeURLHost {
            get {
                return ResourceManager.GetString("ComputeURLHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost:84.
        /// </summary>
        internal static string ComputeURLLocalHost {
            get {
                return ResourceManager.GetString("ComputeURLLocalHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkBlueMarbleBar {
            get {
                object obj = ResourceManager.GetObject("DarkBlueMarbleBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkBlueMarbleTile {
            get {
                object obj = ResourceManager.GetObject("DarkBlueMarbleTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DarkMarble {
            get {
                object obj = ResourceManager.GetObject("DarkMarble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_add {
            get {
                object obj = ResourceManager.GetObject("database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_add_small {
            get {
                object obj = ResourceManager.GetObject("database_add_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_process {
            get {
                object obj = ResourceManager.GetObject("database_process", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_search {
            get {
                object obj = ResourceManager.GetObject("database_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Products/Chashavshavon/Chashavshavon_Installer.exe.
        /// </summary>
        internal static string DownloadApplicationURL {
            get {
                return ResourceManager.GetString("DownloadApplicationURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta content=&quot;text/html;charset=UTF-8;&quot; /&gt;
        ///        &lt;title&gt;רשימת וסתות {{DATE}}&lt;/title&gt;
        ///        &lt;style&gt;
        ///            body,
        ///            table,
        ///            td {
        ///                text-align: right;
        ///                direction: rtl;
        ///                font-family: Narkisim;
        ///            }
        ///            body {
        ///                background-image: url(data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4QCsRXhpZgAATU0AKgAAAAgACQEaAAUAAAABAAAAegEbAAUAAAABAAAAggEoAAMAAAABAAIAAAExAAIAAAASAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EntryListHtmlTemplate {
            get {
                return ResourceManager.GetString("EntryListHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Products/Chashavshavon/VERSION.txt.
        /// </summary>
        internal static string GetLatestVersionURL {
            get {
                return ResourceManager.GetString("GetLatestVersionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Luach Project Daily Info&lt;/title&gt;
        ///        &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///        &lt;meta http-equiv=&quot;Content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///            html,
        ///            body {
        ///                height: 100%;
        ///                font-family: Tahoma;
        ///                font-size: 8pt;
        ///                color: #696969;
        ///                margin: 0;
        ///                padding: 5px 5px 0 0;
        ///                direction: rtl;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoHTMLHeb {
            get {
                return ResourceManager.GetString("InfoHTMLHeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightBlueMarble {
            get {
                object obj = ResourceManager.GetObject("LightBlueMarble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:8080.
        /// </summary>
        internal static string LocalAppURL {
            get {
                return ResourceManager.GetString("LocalAppURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;LS&gt;&lt;L N=&quot;Ofakim&quot; H=&quot;אופקים&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;E&gt;170&lt;/E&gt;&lt;LT&gt;31.32&lt;/LT&gt;&lt;LN&gt;-34.62&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Eilat&quot; H=&quot;אילת&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;29.55&lt;/LT&gt;&lt;LN&gt;-34.95&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Elad&quot; H=&quot;אלעד&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;E&gt;150&lt;/E&gt;&lt;LT&gt;32.05&lt;/LT&gt;&lt;LN&gt;-34.95&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Ashdod&quot; H=&quot;אשדוד&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;31.78&lt;/LT&gt;&lt;LN&gt;-34.63&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Ashkelon&quot; H=&quot;אשקלון&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;31.65&lt;/LT&gt;&lt;LN&gt;-34.57&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Be&apos;er Ya&apos;akov&quot; H=&quot;באר יעקב&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;31.93&lt;/LT&gt;&lt;LN&gt;-34.83&lt;/LN&gt;....
        /// </summary>
        internal static string LocationsList {
            get {
                return ResourceManager.GetString("LocationsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_previous {
            get {
                object obj = ResourceManager.GetObject("page_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ParchmentMarbleTile {
            get {
                object obj = ResourceManager.GetObject("ParchmentMarbleTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinkMarbleTile {
            get {
                object obj = ResourceManager.GetObject("PinkMarbleTile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previous {
            get {
                object obj = ResourceManager.GetObject("previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap process {
            get {
                object obj = ResourceManager.GetObject("process", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh1 {
            get {
                object obj = ResourceManager.GetObject("refresh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scroll {
            get {
                object obj = ResourceManager.GetObject("scroll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Services/SendAppErrReport.svc/SendReport.
        /// </summary>
        internal static string SendErrorReportURL {
            get {
                return ResourceManager.GetString("SendErrorReportURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap today {
            get {
                object obj = ResourceManager.GetObject("today", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta content=&quot;text/html;charset=UTF-8;&quot; /&gt;
        ///    &lt;title&gt;לוח חשבשבון
        ///            {{DATE}}
        ///    &lt;/title&gt;
        ///    &lt;style&gt;
        ///        body, table, td { text-align: right; direction: rtl; font-family: Narkisim; }
        ///        body { background-image: url(data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4QCsRXhpZgAATU0AKgAAAAgACQEaAAUAAAABAAAAegEbAAUAAAABAAAAggEoAAMAAAABAAIAAAExAAIAAAASAAAAigMBAAUAAAABAAAAnAMDAAEAAAABAAAAAFEQAAEAAAABAQAAAFERAAQAAAABAAALElESAAQAAAABAAALEgAAAAAAARkvAAAD6AABGS8AAAPoUGF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeekProblemListHtmlTemplate {
            get {
                return ResourceManager.GetString("WeekProblemListHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhiteMarble {
            get {
                object obj = ResourceManager.GetObject("WhiteMarble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
