application: remotechashavshavon
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/userconsole.html 
  upload: static/userconsole.html
  secure: optional
- url: /static/([^A-Z]+)
  static_files: static/\1
  upload: static/.*
  secure: optional
- url: /static/.*
  script: tolowercase.application
  secure: optional
- url: /[A|a]dmin
  script: admin.application
  secure: optional
- url: /.*
  script: main.application
  secure: optional