"C:\Program Files\7-Zip\7z.exe " a "Chashavshavon_Installer.zip" "%~1%~2\*"
"C:\Program Files (x86)\ZipGenius 6\zg.exe" -sfx "Chashavshavon_Installer.zip" A1 B1 O0 E0 L0 C"Setup.exe" D"%temp%" U"ChashInstall" H2 S0 T"Extracting Chashavshavon installation files..."
REM DEL "Chashavshavon_Installer.zip"
MOVE "Chashavshavon_Installer.exe" "D:\repos_git\Compute\WebSite\Products\Chashavshavon\Chashavshavon_Installer.exe"
"C:\Program Files\7-Zip\7z.exe " a "D:\repos_git\Compute\WebSite\Products\Chashavshavon\Chashavshavon_Installer.zip" "D:\repos_git\Compute\WebSite\Products\Chashavshavon\Chashavshavon_Installer.exe"
"SetVersionApp.exe " "D:\repos_git\Chashavshavon\Chashavshavon\bin\%~2\Chashavshavon.exe" "D:\repos_git\Compute\WebSite\Products\Chashavshavon"